### ISSUE TITLE
Write an algorithm to calculate the total magnitude

### ISSUE THREAD

**Issue by crawfordsm** [crawfordsm/lcbg#12]
Following Section 2.5.2 in Crawford 2006, calculate the total magnitudes for the sources.   This will be necessary to determine the half-light radius and the absolute magnitude for the sources.

Except from Crawford 2006: 

Calculation of the total magnitude requires several steps and is an iterative process. Through iteration we are able to improve the removal of contaminating objects, improve sky subtraction, and provide a more precise estimate of ǫ due to improved measurements of the total magnitude and concentration index, which for our purposes depends on the total magnitude. For these com- parison calculations, we use C2080 defined from the total magnitude for our measurement, whereas the “corrected magnitude” of Graham et al. (2005) uses C2080 based on a Petrosian magnitude. Throughout this work, the magnitude derived through the following algorithm is referred to as the “total magnitude.”

• Step 1. Construct the curve of growth (COG) of the light profile. To construct the COG, we use 50, logarithmically spaced, circular apertures from a radius of 0.067 to 14 arcsec with the PHOT task in DAOPHOT. The area of each aperture is estimated from the number of unmasked pixels. To prevent contamination, objects surround the target are masked. Mask sizes are computed from the isophotal area from the initial detection. If the masked area from one object overlaps the target’s masked area, the overlapping area is left unmasked. Bad pixels,
cosmetic defects, and blank regions are also masked.

• Step 2. Correct the COG. The curve of growth is corrected for poor sky subtraction and object contamination. Poor sky subtraction is corrected by requiring the COG to asymptote to a single value at large radii. On subsequent iterations, contaminating flux from nearby objects is subtracted from the COG. For all nearby objects (within 1′ of the target), the amount of unmasked flux contributed to the COG was estimated by integrating over the intersection of the object’s Se`rsic profile (§2.7.4) and each aperture in the COG. The parameters of the profile (n, re, and Ie) are determined from the half-light radius, concentration index, and total magnitude. The objects are subtracted after each iteration using the improved estimate for each object’s parameters to improve the subtraction.

• Step 3. Measure characteristics. For each aperture, the surface brightness, average surface brightness, and η are calculated. We determine rp from the η distribution and then calculate the total magnitude. For the first pass, eta = 2 is used for the calculation of the total magnitude. Finally, we calculate r0.5 and C2080. All values are calculated through interpolating between different apertures in the curve of growth.

• Step 4. Repeat until convergence. Steps 2-3 were repeated until the magnitudes of the objects converged. For these later iterations, ǫ was set based on the concentration index.
The relationship between ǫ, such that the aperture encloses 99% of the light and the con- centration index is plotted in Figure 2.13. This relationship is determined by simulating the Se`rsic equation for different values of n and calculating rp, C2080, and the radius enclosing 99% of the light. This figure is further discussed in §2.7.2. When calculating the total magnitude, we use an ǫ required to measure 98% of the light as this leads to much smaller random errors for objects with large concentrations. Tabulated values for ǫ as a function of concentration index and n for both the 98% and 99% total magnitudes are provided in Table 2.3.

**Comment by robelgeda** [comment]
Closed by #19
